/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpectrumRouteImport } from './routes/spectrum'
import { Route as IndexRouteImport } from './routes/index'

const SpectrumRoute = SpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spectrum': typeof SpectrumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spectrum': typeof SpectrumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spectrum': typeof SpectrumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spectrum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spectrum'
  id: '__root__' | '/' | '/spectrum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpectrumRoute: typeof SpectrumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spectrum': {
      id: '/spectrum'
      path: '/spectrum'
      fullPath: '/spectrum'
      preLoaderRoute: typeof SpectrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpectrumRoute: SpectrumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
